### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dillrich** [JesusFreke/smalidea#1]
Commands I ran: 
$ git clone https://github.com/JesusFreke/smalidea.git
$ cd smalidea
$ ./gradlew build --scan

the gradle scan location: 
https://scans.gradle.com/s/wqedwlc6bm7zm

the fails occured on Task : test

**Comment by JesusFreke** [comment]
Thanks. This should be fixed by 86017532653f3596df4000970fd1d3b6168958eb

(file that one under: how did I ever even build this??)

**Comment by dillrich** [comment]
Cool thanks!
