### ISSUE TITLE
Error install plugin for IDEA/AS

### ISSUE THREAD

**Issue by yihuajack** [JesusFreke/smalidea#11]
According to the instruction I downloaded smali-2.4.0.jar, but when I choose Plugin->Install Plugin from Disk... and choose this file, it gives me an error: Fail to load plugin descriptor from file smali-2.4.0.jar. The problem occurs both in IDEA and AS. How to solve it?

**Comment by gneL1** [comment]
要安装的插件是smalidea.zip  不是smali-2.4.0这个jar包   在https://bitbucket.org/JesusFreke/smali/downloads/  下载smalidea-0.05.zip

**Comment by gneL1** [comment]
> According to the instruction I downloaded smali-2.4.0.jar, but when I choose Plugin->Install Plugin from Disk... and choose this file, it gives me an error: Fail to load plugin descriptor from file smali-2.4.0.jar. The problem occurs both in IDEA and AS. How to solve it?

要安装的插件是smalidea.zip 不是smali-2.4.0这个jar包 在https://bitbucket.org/JesusFreke/smali/downloads/ 下载smalidea-0.05.zip
