### ISSUE TITLE
Cannot get local variables in a method

### ISSUE THREAD

**Issue by landicefu** [JesusFreke/smalidea#5]
I have not been using smalidea for some time, but I remember when it hits the break points, I could see the value of local variables v0, v1.., p0, p1...
However, it says internal like this now:
![螢幕快照 2020-04-18 下午1 14 20](https://user-images.githubusercontent.com/375642/79628768-8c686f80-8176-11ea-93d0-d7d0ce4f9fac.png)

EDIT
It does work for objects, but not primitives.

**Comment by JesusFreke** [comment]
Yeah, this is borked in recent versions of Android, but I've heard from others that it's fixed in the R preview.

See, e.g. https://github.com/JesusFreke/smali/issues/737 and https://github.com/JesusFreke/smali/issues/753
