### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Surendrajat** [JesusFreke/smalidea#7]
I see a lot of changes since 31 March 2017. Could you please make a release for this one if these changes are significant enough?

**Comment by detunized** [comment]
@Surendrajat, I forked and made a GH action to build and release on each commit. Here you could download the latest binary: https://github.com/detunized/smalidea/releases

**Comment by Surendrajat** [comment]
@detunized much appreciated! Hopefully you'll open a PR with that GH in this repo as well.

**Comment by detunized** [comment]
@Surendrajat, I could. The problem is it's creating a release for each commit. It would be better to only create releases on tags. @JesusFreke would have to tag the releases.

**Comment by Surendrajat** [comment]
@detunized a continuous build with autotag is also not bad for this project as changes are not frequent. Anyways let's see what @JesusFreke decides.

**Comment by JesusFreke** [comment]
v0.06 is out
